spring.application.name=sportLoan

spring.data.mongodb.uri=mongodb+srv://cristiansperilla:Cr042810.@cluster0.2hf2j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&ssl=true

spring.data.mongodb.database=Cluster0
